### ISSUE TITLE
Asset loader issues - combined ticket

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#229]
There are a lot of open issues with the asset loader.

Most important, phase 1:
- [x] the "dense" red urban buildings have been redone by gnanasai but have not been updated to the app: https://github.com/3DStreet/3dstreet/issues/180
- [x] Rename `streetmix-assets` to `assets-3dstreet` https://github.com/3DStreet/3dstreet/issues/93
- [x] Co2 asset should be placed in same directory structure as other loud bicycle game assets and also to have it loaded as part of the loud bike assets pack: https://github.com/3DStreet/3dstreet-assets-source/issues/39
- [x] https://github.com/3DStreet/3dstreet/issues/232

Nice to have, phase2:
- [x] Add BRT station asset https://github.com/3DStreet/3dstreet-assets-source/issues/20 to assets.py and application support in processSegments function
- [ ] Do not have duplicates of people https://github.com/3DStreet/3dstreet/issues/199
- [x] Ensure all (non-animated) assets are compressed with draco https://github.com/3DStreet/3dstreet/issues/239
- [x] Add new "arcade" building type: https://github.com/3DStreet/3dstreet-assets-source/issues/21

Later:
- [ ] Needs docs: https://github.com/3DStreet/3dstreet/issues/200

**Comment by kfarr** [comment]
closing this ticket as all open items already have other tickets to track progress
