### ISSUE TITLE
[epic] v0 beauty shot for For Fri 29 Sep event

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#353]
As a user with a street scene with one street I'd like to be able to show one end of that street off as a cross section style animated scene. I'd like for it to represent real life scale and detail of specific elements relevant for street safety. I'd like an easy way to navigate the cross section scene and see labels.

For Fri 29 Sep event - high prio
- [x] KF - 1! camera position at cross section - see ground and street layers as solid elements
- [x] skybox options #360
- [x] - 4! shadow - try v1 from existing scenes such as glitch accelerator throttle scene #339 and #67 
- [x] rails extend too far #363
- [x] add below ground volume to street https://github.com/3DStreet/3dstreet/pull/365/commits/ea2c9e6d4b681c95b17ddf020bca16c9b256d598
- [x] - 3! label - idea1 - use diarmid's component to create label elements - try it out then try using just x coordinate and putting y along bottom of screen or creating dialog box next to it, etc.

For v1 to be complete
- [ ] Prepare for merging above items into main: 
- [ ] shadows
- [ ] skybox options (environment presets)
- [ ] rails width updates
- [ ] volume below street
- [ ] Remove (Not to merge with main for v1): labels, camera position, camera "selfie stick" rotation scheme, street length reduction
- [ ] add below ground volume to ground lots underneath buildings #362 
- [ ] grouped people upon tab switch #364
- [ ] - lighting should be bright daytime -- confirm in new environment types / skybox options

Longer term epic / v2 or beyond
- [ ] Not to merge / add to v2 list: labels, camera position, camera rotation scheme, street length
- [ ] Big fix: https://github.com/3DStreet/3dstreet/issues/357
- LATER - cannot switch between orbit camera and first person / cursor teleport controls
- [ ] segments should be hoverable and selectable
- [ ] segments should be editable instantly without needing to reload the scene
- [ ] - 3.5 label - idea2 - use intersection hover style simiilar to editor and popup small window with information about the item. v1 is just alt text hover
- [ ] - 1.5 elements from scene should be close to the front of the camera position
- [ ] selfie stick camera rotate should support zoom
- [ ] selfie stick camera rotate should support hover to auto pan camera (hover left pan -10º, hover right pan 10º Y for example)
- [ ] - label - idea3 - in-scene plane or text elements

- [ ] - consider how to have reflection
- [ ] - test existing animate flags when importing a streetmix scene - try it out
- [ ] - use clipping plane for animated items - try it out
- [ ] - moving people
- [ ] - new trees
- [ ] - ocean
- [ ] - texture improvement
- [ ] send to render with pathtracing
- [ ] send to stable diffusion et al wrappers
- [ ] environment lightmap https://glitch.com/edit/#!/stack-64241307 and https://stackoverflow.com/questions/64241307/aframe-1-0-4-setting-scene-environment-does-not-update-materials using the hdr originals from the new skies from #360
