### ISSUE TITLE
[epic] v1 Creator Usability - minimum viable planner

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#358]
Persona: Creator (Trail Blazer)

As a professional or first-time Creator...
- I have minimum expectations of usability for cloud SaaS applications -- no broken things! ([save / load reliability addressed in separate Editor epic](https://github.com/3DStreet/3dstreet-editor/issues/259))
- I want to the software to be clear and honest even if it has limitations (reinforce the truth such as dimensions of objects, even if their edit-ability proves challenging at this stage)
- I want to feel proud enough of my created work to share my creation with others and trust their experience will match my expectations

Improving 3dstreet core parser - clear and honest core usability
- [x] #396
- [x] KF - segment x location match reality https://github.com/3DStreet/3dstreet/issues/357
- [x] KF - scene graph: better class / ID / "display names" (ie "Segment 1: Sidewalk" instead of "segment-parent-1")
- [x] KF - segment widths match reality #374
- [x] KF - Should NOT use scaleX / defaultModelWidthsInMeters; instead set segment box width to be width in meters
- [x] KF - v1 rename / restructure building placement in scene graph (see #396)
- [x] AG - fix elevation level support https://github.com/3DStreet/3dstreet/issues/388
- [x] AG - fix cyclist elevation https://github.com/3DStreet/3dstreet/issues/383 #387 
- [x] KF - make ocean block ocean https://github.com/3DStreet/3dstreet/issues/379
- [x] KF - brown box beneath lot grounds https://github.com/3DStreet/3dstreet/issues/362
- [x] KF - Next pass at building / ground refactor - show Block1 and Block2 as separate - see #396 

User interface behaves as expected
- [x] AG - viewer mode icons should be hidden when in editor mode ([see failed attempt here](https://github.com/3DStreet/3dstreet/pull/368/commits/cd176ebcae2cf9082a5cb19df0be9a47b6d4fc96))
- [x] AG hide viewer icons and viewer title in editor mode #369
- [x] KF - always white text for scene graph entity names instead of varying text by class or id or other attribute https://github.com/3DStreet/3dstreet-editor/commit/53b04b633939f6e0a7b337138bf0e80dc9bf4554

Visual quality meets my minimum expectations:
- [x] KF - shadows (cherry pick from beauty shot)
- [x] AG - ground material roughness https://github.com/3DStreet/3dstreet/issues/340
- [x] KF - new skybox (cherry pick from beauty shot)
- [x] KF - rails extend too far https://github.com/3DStreet/3dstreet/issues/363
- [x] KF - below ground volume (cherry pick from beauty shot)
- [x] KF - add shadow casting light to other presets (copy `light2` entity from day preset)
- [x] KF - new rails object / rails width updates to match IRL standard gauge and cable cars
- [x] AG - fix car animation https://github.com/3DStreet/3dstreet/issues/386
- [x] AG - self driving car https://github.com/3DStreet/3dstreet/pull/392
- [x] AG - automatic vehicle movement
- [x] AG - color environment option https://github.com/3DStreet/3dstreet/issues/337
- [x] AG - more outdoor dining prop https://github.com/3DStreet/3dstreet/issues/375
- [x] #416
- [x] Remove animation from default
- [x] #421
- [x] Upgrade to A-Frame 1.5
- [x] Deploy checklist

Longer-term epic / future tickets
see https://github.com/3DStreet/3dstreet/issues/447

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet/releases/tag/0.4.5
