### ISSUE TITLE
epic v2 creator usability

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#447]
As a professional or first-time Creator...
- I perform specific "jobs to be done" in 3DStreet that have associated bugs or do not work as expected
- I want the application to behave as I expect, or otherwise notify me.

Visual:
- regression: center shared turn lane, inconsistent scaling of dashed lines

Enhancements:
- [ ] snapping - start with y axis "snap to ground" for v1 https://github.com/3DStreet/3dstreet/issues/385

Refactor:
- [ ] KF - scene graph (Editor API) change data-layer-display-name to just data-display-name
- do not use planes for segment ground anywhere except separator markers or stencils. Double check segment type 'divider' does not have any planes.

- [ ] KF - camera position v1 (new orbit controls - cherry pick from beauty shot). Default position to encompass entire length of scene (radius of selfie stick to correlate with street width). As a user I can use scroll wheel motion to "zoom out" to see all of the blocks on each side, and "zoom in" to see an individual segment. As a user I can use scroll wheel left/right to move the centerpoint from left to right (ie if I'm zoomed in, scroll left/right effectively changes which segment is in view)
- [ ] AG and/or Zade - model categories https://github.com/3DStreet/3dstreet/issues/373
- [ ] AG - migrate to STREET global in 3dstreet repo #390 and #394 
- https://github.com/3DStreet/3dstreet/issues/407
- [ ] KF - scene graph (Editor API) change data-layer-display-name to just data-display-name
- [ ] KF - segments should have labels v2 - add learnings from Scott's friend for a v2
- [ ] add another street https://github.com/3DStreet/3dstreet/issues/377
- https://github.com/3DStreet/3dstreet/issues/372
- segments should be hoverable and selectable
- segments should be editable instantly without needing to reload the scene
