### ISSUE TITLE
[epic] CSS Improvement and storybook v1

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#578]
Timebox 1 hour:
Next step - more detail for first 4 tickets -- time estimation and exactly which files will be modified for first ~4 fickets (330-333) for example. Please update via the tickets created below. 

@ViktoriaShurhot 

****

CSS Project goal
- as a developer I want best practices for css templating so that I don't have to struggle with different tools and unorganized css files
- as a designer I want confidence that components were implemented per my specification
- as a contributor / user I want to see that the 3dstreet application is robust and extensible (aka well maintained)

Therefore 2 goals:
- improve css code quality
- create one page that a user can see (publicly, on the internet, not just hosted) that shows all the components that the application can use, similar to storybook (or even use storybook)

Proposal:
- interweave delivery of adding new storybook components in parallel to other css refactoring work

Example steps:
- [x] 3DStreet/3dstreet-editor#338
- [x] 3DStreet/3dstreet-editor#330
- [x] 3DStreet/3dstreet-editor#331
- [x] 3DStreet/3dstreet-editor#332
- [x] 3DStreet/3dstreet-editor#333
- [x] 3DStreet/3dstreet-editor#334
- [ ] 3DStreet/3dstreet#579
- [ ] 3DStreet/3dstreet#580
- [ ] 3DStreet/3dstreet#581
- [ ] 3DStreet/3dstreet#582
- [ ] 3DStreet/3dstreet#583
- [ ] 3DStreet/3dstreet#584

original source proposal: https://docs.google.com/document/d/1-LuznYMrMYrTMhXIA8uigDAhyzhqaYFfjavWaxaTyRE/edit
